version: "3.8"

x-common-app-settings: &common-app-settings
  build:
    context: .
  depends_on:
    - redis
    - mongodb

x-base-environment: &base-environment
  REDIS_URL: ${REDIS_URL}
  MONGO_URI: ${MONGO_URI}
  MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  S3_ACCESS_KEY: ${S3_ACCESS_KEY}
  S3_SECRET_KEY: ${S3_SECRET_KEY}
  S3_ENDPOINT: ${S3_ENDPOINT}
  S3_BUCKET: ${S3_BUCKET}

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  mongodb:
    hostname: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=etternizer
    restart: unless-stopped

  api:
    <<: *common-app-settings
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *base-environment
      API_PORT: ${API_PORT}

volumes:
  mongodb_data:
  redis_data:
